### ISSUE TITLE
Not a bug > Project stability?

### ISSUE THREAD

**Issue by saurabhnanda** [ramontayag/liquid_stream#3]
Hi, I'm using Liquid templates in a production system and am trying to solve the same problem that the liquid_stream project solves. However, I'm a little worried about the stability of this project (because it's hardly a month old).

Would you recommend using liquid_streams in a production system (not a toy project, etc)?

**Comment by ramontayag** [comment]
Hi @saurabhnanda, while I intend to maintain it, I suppose just like any open source project I can't promise you that this will be here forever. If this project goes unmaintained you can always fork it and use your fork. The code is not very readable because of the necessary meta programming portions, but the consolation is that it's short.

I would recommend you playing around with it first before using it in a production system. It's not a toy project. I am currently migrating a project of mine to use this one.

Did I answer all your questions?

**Comment by saurabhnanda** [comment]
I understand that this is a volunteer-driven effort and cannot be taken for granted.  I was just worried about pushing incomplete / untested code into a production system.

I'm trying a couple of approaches to solve the same problem, but am probably leaning towards a different approach. Building a PoC and seeing how that solution evolves.

Thank you for `liquid_stream`, I'm sure I'll use it in the near future.

**Comment by ramontayag** [comment]
I think it's well tested. Take a look at it and see if I missed anything :) If you want to work on this I'm free to remote pair sometime.
